Migrate Launcher to new ECS deploy module
ONSdigital/eq-terraform pull request #101
Opened 2017-10-16 10:25 UTC by jonnyshaw89

### What is the context of this PR?
This allows us to override the docker registry and container tag.

### How to review
get the latest updates `terraform get -update`
run `terraform apply` and check that go-launch-a-survey deploys and works correctly

2017-10-16 11:09 UTC, MIslam92 approved these changes
Ran & Deployed to AWS fine 👍

2017-10-17 08:39 UTC, ajmaddaford approved these changes

2017-10-17 08:40 UTC, ajmaddaford requested changes
All looks good, but can't be merged until https://github.com/ONSdigital/eq-ecs-deploy/pull/2 merges and the branch reference in this pull request is removed

2017-10-17 16:12 UTC, ajmaddaford approved these changes

2017-10-17 16:12 UTC, merged