Add Firebase authentication configuration for author
ONSdigital/eq-terraform pull request #110
Opened 2018-01-05 15:16 UTC by ajmaddaford

### What is the context of this PR?
Added ability to provide Firebase authentication for Author as implemented in https://github.com/ONSdigital/eq-author/pull/273

### How to review
- Run eq-terraform and verify auth is disabled by default
- Get some firebase credentials and add them to your terraform.tfvars:
  ```
  author_skip_auth = "false"
  author_firebase_project_id = "<your project id>"
  author_firebase_api_key = "<your api key>"
  author_firebase_messaging_sender_id = "<your sender id>"
  ```
- Run terraform apply and verify logging in via Firebase works

2018-01-05 15:19 UTC, ajmaddaford commented
This pull request is dependent on https://github.com/ONSdigital/eq-author/pull/273 and https://github.com/ONSdigital/eq-author-deploy/pull/7. Once those have merged the references in this pull request to those branches needs to be removed.

2018-01-05 16:14 UTC, ajmaddaford commented
![](https://github.trello.services/images/mini-trello-icon.png) [Integrate user sign in](https://trello.com/c/itrglzyg/296-integrate-user-sign-in)

2018-01-10 15:28 UTC, jonnyshaw89 requested changes

2018-01-10 15:28 UTC, jonnyshaw89 commented on developer_defaults.tf
> +  default = "false"
Formatting needs fixing here

2018-01-10 16:39 UTC, jonnyshaw89 approved these changes

2018-01-11 14:00 UTC, MIslam92 approved these changes
Just point source back to master and "Squishy Squashy"

2018-01-11 14:03 UTC, jonnyshaw89 commented
@MIslam92 that branch isn't merged yet so this can't be merged https://github.com/ONSdigital/eq-author-deploy/pull/7

2018-01-11 15:05 UTC, merged