Add output for the schema validator for ecs.
ONSdigital/eq-terraform pull request #115
Opened 2018-02-08 07:44 UTC by samiwel

### What is the context of this PR?
Added a new output to the terraform config for schema validator.
This is required for an upcoming change to Publisher so that it may use the eq-schema validator.

### How to review
Ensure changes to terraform config are correct.

### Related PRs
 - https://github.com/ONSdigital/eq-author-deploy/pull/8

2018-02-08 08:24 UTC, samiwel commented
![](https://github.trello.services/images/mini-trello-icon.png) [Use schema-validator in eq-publisher (3)](https://trello.com/c/rLjImix1/368-use-schema-validator-in-eq-publisher-3)

2018-02-08 09:31 UTC, jonnyshaw89 requested changes

2018-02-08 09:31 UTC, jonnyshaw89 commented on survey-runner.tf
> +output "survey_validator_for_ecs" {
This doesn't need to be an output, it needs to be added here. https://github.com/ONSdigital/eq-terraform/pull/115/files#diff-964611b37b257ebaffb6708a708955f4R175

2018-02-12 12:55 UTC, jonnyshaw89 approved these changes

2018-02-12 13:30 UTC, merged