Default min number of ECS Service container tasks to 1 for developers
ONSdigital/eq-terraform pull request #119
Opened 2018-02-16 12:29 UTC by dwyeradam

To override for developer environments the defaults defined by the following PRs:
https://github.com/ONSdigital/eq-ecs-deploy/pull/8
https://github.com/ONSdigital/eq-author-deploy/pull/10
https://github.com/ONSdigital/eq-survey-runner-deploy/pull/17

2018-02-16 12:31 UTC, dwyeradam commented
@jonnyshaw89 is there a reason we're currently tied to v1.0.0 for eq-ecs-deploy?

2018-02-16 13:24 UTC, jonnyshaw89 commented
@dwyeradam just so it’s tied to a release version. You can create a new release version and point to that

2018-02-19 10:56 UTC, jonnyshaw89 requested changes

2018-02-19 10:56 UTC, jonnyshaw89 commented on developer_defaults.tf
> +variable "application_min_tasks" {
We shouldn't reuse this variable, we should have one for each service.

2018-02-19 12:55 UTC, jonnyshaw89 approved these changes

2018-02-20 10:09 UTC, MIslam92 approved these changes
'Squishy Squashy'

2018-02-20 11:21 UTC, merged