Slack alert Lambda not working on preprod for state change notifications
ONSdigital/eq-terraform pull request #131
Opened 2018-06-18 08:51 UTC by nealedj

### What is the context of this PR?
State change notifications were not generating slack alerts on preprod. On prod we seem to have multiple functions.

This function serves both SNS notifications and direct cloud watch alerts. It also removes the previously hard-coded environment string that was present in the deployed version.

2018-06-18 14:12 UTC, jonnyshaw89 requested changes

2018-06-18 14:12 UTC, jonnyshaw89 commented on survey-runner-alerting/lambda/slack-alert/index.js
> +         alertState = event.detail.state;
How are these events triggered?

2018-06-18 14:12 UTC, jonnyshaw89 commented on survey-runner-alerting/lambda/slack-alert/index.js
> +     } else {
I don't like `else` we should split this out into a function

2018-06-19 07:27 UTC, shahi645 commented
@nealedj I see an error sometimes when i do `terraform apply` to do with a slack alert lambda. Is this the same thing?

2018-06-19 08:04 UTC, closed without merging

2018-06-19 08:04 UTC, nealedj commented
Closing so this can be reimplemented as two functions.