Treat missing rabbit cluster data as missing - not breaching
ONSdigital/eq-terraform pull request #137
Opened 2018-07-25 10:12 UTC by nealedj

### What is the context of this PR?
The rabbit instances both run a script every 5 minutes that pushes a metric to CloudWatch (0 or 1 depending if the cluster is healthy or not). If the metric does not get pushed then we treat it as a breach and alert to Slack.

The issue here is that on a reasonably frequent basis the alarm is unable to query that metric data and this results in a Slack alert even though the cluster is perfectly healthy.

### How to review
Push to personal AWS environment. Ensure that the x-rabbitmq1-cluster-alert and x-rabbitmq2-cluster-alert have their "Treat missing data as:" setting set to "missing" and not "breaching"

2018-07-25 10:14 UTC, jonnyshaw89 approved these changes

2018-07-26 09:35 UTC, kierenbeckett requested changes
I'm worried this means if our scripts fail to push any metrics we won't know about it, could we increase the evaluation periods instead?

2018-07-26 09:47 UTC, jonnyshaw89 commented
We have another status alarm that will alert us if it stops working completely. evaluation period may add more tolerance.
Ideally we just need to bin these and use managed queues with better metrics

2018-07-26 09:53 UTC, kierenbeckett commented
Do you mean `rabbitmq_status `?

2018-07-26 09:58 UTC, jonnyshaw89 commented
@kierenbeckett possibly, I think its just a EC2 check that the box is there.
there is a lot to be desired from these queues and most of it hasn't been done as we have always been "about to change them"

2018-07-26 09:58 UTC, nealedj commented
Might increasing the evaluation period have the effect of delaying the alarm from firing when there actually is a problem? Will it matter that much if it's 20 mins instead of 5?

We'd need to increase it to at least 15 I think - because we've definitely seen the metrics fail to be recognised for at least 2 periods (10 mins)

2018-07-26 10:04 UTC, kierenbeckett commented
The stat is set to Maximum, so only one of the datapoints needs to be a 1 for it to ALARM.

2018-07-26 10:07 UTC, kierenbeckett commented
If the other status alarm is `rabbitmq_status`, this only helps us if the whole EC2 instance fails, not if the script on it fails

2018-07-26 10:07 UTC, jonnyshaw89 commented
If it ever does go down we will get the 5xx alarm from runner before any alarm from here any way so its not gonna let us know early

2018-07-30 07:52 UTC, nealedj commented
@jonnyshaw89 @kierenbeckett what shall we do with this? Increase the evaluation period to 3?

2018-07-30 07:57 UTC, jonnyshaw89 commented
🤷‍♂️

2018-07-30 08:38 UTC, kierenbeckett approved these changes

2018-07-30 08:52 UTC, jonnyshaw89 commented
Have we checked that 3 evaluation periods is enough?

2018-07-31 13:02 UTC, nealedj commented
@jonnyshaw89 I guess the only way we'll know is to try it.

2018-07-31 13:08 UTC, jonnyshaw89 commented
@nealedj we could look at the size of the datapoint gap in CloudWatch?

2018-08-02 08:45 UTC, nealedj commented
Looking at the gap this morning it was missing data at 0535 until 0545 - 2 periods. I.e. the metrics expected at 0535 and 0540 were missing but the one at 0545 was found.

2018-08-02 15:42 UTC, jonnyshaw89 commented
@nealedj do you want to squash this branch then?

2018-08-03 08:45 UTC, merged