User t3 instances for ECS
ONSdigital/eq-terraform pull request #145
Opened 2018-09-18 10:44 UTC by jonnyshaw89

- They are cheaper and faster
 - Removed the max limits on DynamoDB

### How to review
Run it and see that it continues to work as expected.

2018-09-18 11:13 UTC, bitdivision requested changes

2018-09-18 11:13 UTC, bitdivision commented on survey-runner.tf
> +  submitted_responses_min_read_capacity  = 1
duplicate line?

2018-09-18 14:55 UTC, bitdivision approved these changes

2018-09-19 08:27 UTC, samiwel approved these changes

2018-09-19 11:25 UTC, merged