Fix LB for modules to internal ALB.
ONSdigital/eq-terraform pull request #154
Opened 2018-11-27 11:05 UTC by bitdivision

### What is the context of this PR?
eq-terraform-ecs has been changed to support internal and external load balancers.

This PR updates eq-terraform to handle this.

Since eq-terraform is only used for dev, we can set all modules to use the external load balancer and disable the internal load balancer entirely.

### How to review
Deploy it and make sure everything still works?

2018-11-27 11:13 UTC, bitdivision commented on survey-runner.tf
> +  source                   = "github.com/ONSdigital/eq-terraform-ecs?ref=internal-alb"
Will need to remove the branch before this gets merged.

2018-11-28 11:03 UTC, jonnyshaw89 approved these changes

2018-11-28 14:57 UTC, MebinAbraham approved these changes
Looks like everything is still standing... 🤷‍♂️

2018-11-29 12:24 UTC, ajmaddaford requested changes

2018-11-29 12:24 UTC, ajmaddaford commented on developer_defaults.tf
> +
I think it would be clearer if these were named `create_` rather than `use_` as which load balancer is used is determined at the point an app is deployed into the ECS cluster.

2018-11-29 12:35 UTC, bitdivision commented on developer_defaults.tf
> +
Very true. Fixed here and in ecs module.

2018-12-04 16:12 UTC, ajmaddaford approved these changes

2018-12-04 16:12 UTC, merged