Updating documentation
ONSdigital/eq-terraform pull request #61
Opened 2017-01-27 16:07 UTC by benjefferies

### What is the context of this PR?
* Updating missing documentation in readme
* Adding aws profile support
* Adding more non-sensitive variables to template

### How to review
Describe the steps required to test the changes.

- [ ] Do all commits have sensible commit messages?
- [ ] Is there documentation or is the code self-describing?
- [ ] Test by deploying environment

2017-01-27 17:11 UTC, collisdigital commented on survey-runner/terraform.tfvars.example
> +schema_bucket="eq-schema-files-XXXXX" # Set to your schema bucket
Is this use anymore, now that S3 has been removed?

2017-01-27 17:49 UTC, benjefferies commented on survey-runner/terraform.tfvars.example
> +schema_bucket="eq-schema-files-XXXXX" # Set to your schema bucket
Not sure if it's being used for the author but can probably go if author in its current form is dead

2017-02-01 19:53 UTC, ajmaddaford requested changes

2017-02-01 19:53 UTC, ajmaddaford commented on survey-runner/run-terraform.sh
> +if [ -n "$AWS_DEFAULT_PROFILE" ]; then
I think `AWS_DEFAULT_PROFILE` confuses this with the the default AWS profile you when you don't provide a profile to the aws cli, any reason not to use `AWS_PROFILE`?

2017-02-01 19:53 UTC, ajmaddaford commented on survey-runner/terraform.tfvars.example
>  google_analytics_code="UA-56892037-7"
I think the default value for `google_analytics_code` should be `""`. That should mean that eq-survey-runner doesn't setup analytics (https://github.com/ONSdigital/eq-survey-runner/blob/master/app/__init__.py#L113)
Also it's duplicated below set to `XXXXXXX`

2017-02-08 09:27 UTC, jonnyshaw89 requested changes

2017-02-08 09:27 UTC, jonnyshaw89 commented on README.md
> +  - If using awscli profile export an `AWS_DEFAULT_PROFILE` environment variable e.g. `export AWS_DEFAULT_PROFILE=ons`
probably need to add a note that this step is only required if running multiple AWS profiles

2017-02-08 09:27 UTC, jonnyshaw89 commented on survey-runner/terraform.tfvars.example
>  google_analytics_code="UA-56892037-7"
Agreed, this will taint any analytics received otherwise

2017-02-13 10:19 UTC, benjefferies commented on survey-runner/terraform.tfvars.example
>  google_analytics_code="UA-56892037-7"
Done

2017-02-13 10:19 UTC, benjefferies commented on survey-runner/run-terraform.sh
> +if [ -n "$AWS_DEFAULT_PROFILE" ]; then
Removed this as it's not needed if you set the default profile

2017-02-13 10:19 UTC, benjefferies commented on README.md
> +  - If using awscli profile export an `AWS_DEFAULT_PROFILE` environment variable e.g. `export AWS_DEFAULT_PROFILE=ons`
Done

2017-02-13 11:20 UTC, jonnyshaw89 approved these changes

2017-02-13 12:16 UTC, ajmaddaford approved these changes

2017-02-13 12:16 UTC, merged