Eq 854 split into separate terraform scripts
ONSdigital/eq-terraform pull request #62
Opened 2017-02-14 09:08 UTC by ajmaddaford

### Important 
- Before checking this out and running it, ensure you tear down your existing AWS environment using the current Terraform scripts (on master)

### What is the context of this PR?
Splits the existing Terraform into separate scripts for VPC, routing, database, queue and application. 

The VPC and internet gateway has been split from the routing (subnets, NAT gateways and route tables) as in some environments (pre-prod, production) the VPC already exists (potentially peered to another VPC). An attempt was made to make these conditional in the routing Terraform, but there doesn't seem to be a way when creating a resource to have properties use either a variable or a conditionally created resource. 

Splitting the database, queue and application allows independent creation and destruction, so we can deploy application infrastructure changes without tearing down the database or queues.

There are a number of networking changes:
- There is now provision for 3 public, 3 application and 3 database subnets split across 3 availability zones. The number of subnets created for each is dependent on the number of CIDR blocks given at build time. This allows a reduced developer build in only one availability zone.
- There is a queue subnet which has routes propagated from the Virtual Private Gateway for connections from SDX. This subnet hasn't been split into two as there is a requirement for the queues to keep their existing static IPs (.15 and .16) requiring the subnet range to span these IPs.
- The public subnets have a NAT gateway in each, these are used to access the internet during elastic beanstalk builds
- The application has been moved into private subnets, accessed from load balancers in public subnets
- The Terraform now also turns on route propagation on the queue route table so that SDX connectivity will work without manual intervention after a build

### How to review
- Check out and build - `export AWS_ENVIRONMENT_NAME=<name>; ./survey_runner.sh plan/apply/destroy`
- Deploy the application and verify that it works, including submission to the queues

2017-02-15 11:06 UTC, jonnyshaw89 requested changes

2017-02-15 11:06 UTC, jonnyshaw89 commented on survey-runner-application/security_groups.tf
> +  ingress {
do we use both secure and insecure ports?

2017-02-15 11:06 UTC, jonnyshaw89 commented on survey-runner-application/security_groups.tf
> +  egress {
do we want this open on egress interface?

2017-02-15 11:06 UTC, jonnyshaw89 commented on survey-runner-database/cloudwatch.tf
> +  statistic           = "Average"
if we use space quickly we won't know until its too late. maybe this should be Minimum?

2017-02-15 11:06 UTC, jonnyshaw89 commented on survey-runner-database/database.tf
> +  allocated_storage       = 10
Is that enough?

2017-02-15 11:06 UTC, jonnyshaw89 commented on survey-runner-queue/cloudwatch.tf
> +  comparison_operator = "GreaterThanOrEqualToThreshold"
Isn't this the binary status that is either 1 or 0? so won't it always equal 1 when its alive?

2017-02-15 11:06 UTC, jonnyshaw89 commented on survey-runner-queue/security_groups.tf
> +  egress {
do we ever want to cluster on the external interface?

2017-02-15 11:06 UTC, jonnyshaw89 commented on survey-runner-queue/security_groups.tf
> +  egress {
same comment here about this being egress?

2017-02-15 11:06 UTC, jonnyshaw89 commented on survey-runner-queue/security_groups.tf
> +  ingress {
and do we want insecure port open?

2017-02-15 15:37 UTC, ajmaddaford commented on survey-runner-database/cloudwatch.tf
> +  statistic           = "Average"
Good spot. Fixed.

2017-02-15 15:37 UTC, ajmaddaford commented on survey-runner-database/database.tf
> +  allocated_storage       = 10
Possibly not. I've made it configurable so we can choose whatever storage is appropriate per environment.

2017-02-15 15:37 UTC, ajmaddaford commented on survey-runner-queue/cloudwatch.tf
> +  comparison_operator = "GreaterThanOrEqualToThreshold"
No, the metric reports 0 when it is ok, and 1 if there are any RabbitMQ partitions. This hasn't been changed in this pull request, just moved. 

Looking at https://github.com/ONSdigital/eq-messaging/blob/master/ansible/tasks/cluster_status.sh it tries to work out if the cluster is ok by looking for lines in `rabbitmqctl cluster_status` that contain `{partitions,[]}`. If this exists then the cluster is ok, as otherwise the partitions would appear in the `[]`.  It's pretty horrible!

2017-02-15 15:37 UTC, ajmaddaford commented on survey-runner-queue/security_groups.tf
> +  ingress {
Insecure port removed

2017-02-15 15:37 UTC, ajmaddaford commented on survey-runner-application/security_groups.tf
> +  ingress {
I've removed all explicit ports as there is a rule that allows egress for everything (needed for the Elastic Beanstalk builds)

2017-02-15 15:37 UTC, ajmaddaford commented on survey-runner-application/security_groups.tf
> +  egress {
I've removed all explicit ports as there is a rule that allows egress for everything (needed for the Elastic Beanstalk builds)

2017-02-15 15:37 UTC, ajmaddaford commented on survey-runner-queue/security_groups.tf
> +  egress {
No, I've changed this to use the queue_cidrs.

2017-02-15 15:37 UTC, ajmaddaford commented on survey-runner-queue/security_groups.tf
> +  egress {
The egress rule is as it was before, now limited to the queue subnet.

2017-02-16 15:47 UTC, jonnyshaw89 requested changes

2017-02-16 15:47 UTC, jonnyshaw89 commented on survey-runner-application/terraform.tfvars.example
> +elastic_beanstalk_aws_key_pair="andrew"
your name here.

2017-02-17 09:56 UTC, jonnyshaw89 commented
I seem to be getting error trying to destroy the stack.

`Error applying plan:

1 error(s) occurred:

* aws_vpc.survey_runner: DependencyViolation: The vpc 'vpc-2b310e4f' has dependencies and cannot be deleted.
	status code: 400, request id: 969ae75c-60bf-4a08-b293-2b8593d65204`

2017-02-17 10:24 UTC, ajmaddaford commented on survey-runner-application/terraform.tfvars.example
> +elastic_beanstalk_aws_key_pair="andrew"
Removed

2017-02-17 11:33 UTC, jonnyshaw89 commented
@ajmaddaford were you going to default to not having a key pair, as discussed earlier?

2017-02-17 14:13 UTC, jonnyshaw89 approved these changes

2017-02-20 11:55 UTC, merged