Enable cloudwatch logging
ONSdigital/eq-terraform pull request #63
Opened 2017-02-20 12:31 UTC by jonnyshaw89

### What is the context of this PR?
Enable Cloudwatch logging from elastic beanstalk

### How to review
Are logs available in cloudwatch

2017-02-20 13:59 UTC, benjefferies requested changes
https://github.com/ONSdigital/eq-terraform/blob/master/survey-runner-application/survey_runner.tf#L192 Can be removed

2017-02-20 17:42 UTC, ajmaddaford approved these changes

2017-02-21 10:47 UTC, benjefferies requested changes

2017-02-21 10:47 UTC, benjefferies commented on survey-runner-application/global_vars.tf
> +  default     = "64bit Amazon Linux 2016.09 v2.3.1 running Python 3.4"
This should be changed under a separate commit. It will be confusing in the history otherwise

2017-02-21 14:40 UTC, benjefferies approved these changes

2017-02-21 14:46 UTC, merged