Make database version configurable
ONSdigital/eq-terraform pull request #68
Opened 2017-02-24 15:33 UTC by ajmaddaford

### What is the context of this PR?
Makes the database version configurable. The default has been set to 9.4.9 as we use 9.4.x in production and 9.5.x will not run on the db.m1.small instances we use in development. 

### How to review
Run database Terraform and verify database version changes are applied in AWS

2017-02-24 15:34 UTC, jonnyshaw89 commented
Is it wise to switch between versions between environments. will 9.5.x run on t2 instances?

2017-02-27 09:51 UTC, jonnyshaw89 requested changes

2017-02-27 09:51 UTC, jonnyshaw89 commented on survey-runner-database/terraform.tfvars.example
> +database_allocated_storage = 10
this needs to be at least 100

2017-02-28 11:44 UTC, ajmaddaford commented on survey-runner-database/terraform.tfvars.example
> +database_allocated_storage = 10
No it doesn't 😛

2017-02-28 11:52 UTC, jonnyshaw89 commented on survey-runner-database/terraform.tfvars.example
> +database_allocated_storage = 10
gp2 minimum storage is 100 so i guess it defaults higher but its good to be explicit :)

2017-03-03 11:12 UTC, ajmaddaford commented on survey-runner-database/terraform.tfvars.example
> +database_allocated_storage = 10
From http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html#Concepts.Storage
> A gp2 volume can range in size from 1 GiB to 16 TiB.

2017-03-03 12:35 UTC, benjefferies requested changes

2017-03-03 12:35 UTC, benjefferies commented on survey-runner-database/global_vars.tf
> +    default     = true
Should this be false until we want to upgrade?

2017-03-03 13:25 UTC, ajmaddaford commented on survey-runner-database/global_vars.tf
> +    default     = true
Done

2017-03-03 15:54 UTC, benjefferies approved these changes

2017-03-06 10:47 UTC, jonnyshaw89 commented on survey-runner-database/terraform.tfvars.example
> +database_allocated_storage = 10
I stand corrected. This must have changed from when they were first launched.

2017-03-06 10:48 UTC, jonnyshaw89 approved these changes

2017-03-06 10:48 UTC, jonnyshaw89 commented
@ajmaddaford rebase & squash?

2017-03-06 16:18 UTC, merged