Change default application log level to info
ONSdigital/eq-terraform pull request #71
Opened 2017-03-15 15:09 UTC by ajmaddaford

Changes the default application log level to `INFO`. This is the log level we use in production now as the information it provides is used across the data collection platform to track a respondents journey and generate metrics for dashboards.

### How to review
- Remove any setting of `eq_sr_log_level` from your application terraform.tfvars file
- Deploy survey runner
- Verify that `INFO` log events appear in the logs

2017-03-15 15:24 UTC, jonnyshaw89 requested changes

2017-03-15 15:24 UTC, jonnyshaw89 commented on survey-runner-application/global_vars.tf
>  variable "eq_sr_log_level" {
a good time to rename this and remove the sr?

2017-03-17 15:49 UTC, benjefferies approved these changes

2017-03-20 08:48 UTC, ajmaddaford commented on survey-runner-application/global_vars.tf
>  variable "eq_sr_log_level" {
Yes. Done.

2017-03-20 09:23 UTC, jonnyshaw89 requested changes

2017-03-20 09:23 UTC, jonnyshaw89 commented on survey-runner-application/terraform.tfvars.example
> +eq_log_level="DEBUG"
if someone uses this example file will it override the level to DEBUG? therefore not default it to INFO.

2017-03-20 10:32 UTC, ajmaddaford commented on survey-runner-application/terraform.tfvars.example
> +eq_log_level="DEBUG"
The example file is full of developer defaults to enable developers to get up and running quickly.

2017-03-20 10:43 UTC, jonnyshaw89 approved these changes

2017-03-20 10:55 UTC, jonnyshaw89 commented
@ajmaddaford squash?

2017-03-21 15:39 UTC, merged