Added ECS cluster to run go-launch-a-survey
ONSdigital/eq-terraform pull request #79
Opened 2017-05-09 08:26 UTC by jonnyshaw89

### What is the context of this PR?
I have added an ECS cluster to run the EQ Dev page.
This will in future allow us to remove the "dev" logic from the main EQ application

### How to review
Run the terraform scripts and navigate to the url that is output after the`survey-runner-ecs-application` has run. This will launch the new "dev" page that should redirect to the EQ application running in beanstalk.

2017-05-09 09:13 UTC, collisdigital requested changes

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-application/global_vars.tf
> -variable "rabbitmq_admin_user" {
should these changes be here?

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/alb.tf
> +//resource "aws_route53_record" "survey_runner" {
Remove?

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/ecs.tf
> +    container_port = 5000
is this still running the Flask web server or gunicorn etc?

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/ecs.tf
> +    container_port = 8000
Would be good to TLS this up at some point

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/ecs.tf
> +  image_id               = "ami-175f1964"
where's this AMI from, comment would be good.

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/ecs.tf
> +  user_data              = "#!/bin/bash\necho ECS_CLUSTER=${aws_ecs_cluster.survey_runner.name} > /etc/ecs/ecs.config"
looks nasty, could it be a separate shell script ?

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/ecs.tf
> +  min_size             = 1
can this be overridden in tfvars etc?

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/global_vars.tf
> +  description = "The environment you wish to use"
e.g. .....

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/global_vars.tf
> +  description = "The survey runner VPC ID"
There's a mix of variables here, so which can/should be overwritten and some that shouldn't, would be good to split/clearly identify them as such?

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/global_vars.tf
> +  default     = "Z2XIERRF1SJEYP"
Where's this one from, should it be here?

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/global_vars.tf
> +  description = "The address of the postgres database"
examples for all of these would be good

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/global_vars.tf
> +  default     = "digitaleq12345"
maybe no default?

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/global_vars.tf
> +  default     = "digitaleq12345"
no default?

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/iam.tf
> +        "arn:aws:s3:::elasticbeanstalk-*",
still need EB stuff?

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/iam.tf
> +        "cloudwatch:*"
seems a bit broad?

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/iam.tf
> +  policy = "${data.aws_iam_policy_document.survey_runner.json}"
should all the policies be separate .json files, would be cleaner?

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/outputs.tf
> +//output "survey_runner_address" {
remove?

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/outputs.tf
> +output "survey_runner_launcher_address" {
not sure about the name of this?

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/security_groups.tf
> +    from_port   = "0"
can't we lock this down?

2017-05-09 09:13 UTC, collisdigital commented on survey-runner-ecs-application/terraform.tfvars.example
> +application_secret_key="you'll never guess it"
maybe have these in here but commented out?

2017-05-09 09:17 UTC, jonnyshaw89 commented on survey-runner-application/global_vars.tf
> -variable "rabbitmq_admin_user" {
This variable is never referenced in the application terraform module

2017-05-09 09:17 UTC, jonnyshaw89 commented on survey-runner-ecs-application/alb.tf
> +//resource "aws_route53_record" "survey_runner" {
Can do. I will pull the survey-runner parts into a different branch that will add survey-runner to ecs too.

2017-05-09 09:18 UTC, jonnyshaw89 commented on survey-runner-ecs-application/ecs.tf
> +    container_port = 5000
survey-runner currently doesn't run in this branch as the number of instance is set to 0. so ill pull these changes into another branch

2017-05-09 09:19 UTC, jonnyshaw89 commented on survey-runner-ecs-application/ecs.tf
> +    container_port = 8000
yes it would. I can probably link it up with a certificate from AWS ACM if we have access to the email account to approve the certificates

2017-05-09 09:23 UTC, jonnyshaw89 commented on survey-runner-ecs-application/global_vars.tf
> +  description = "The environment you wish to use"
This is consistent with all of the other modules

2017-05-09 09:25 UTC, jonnyshaw89 commented on survey-runner-ecs-application/global_vars.tf
> +  description = "The survey runner VPC ID"
doesn't the `terraform.tfvars.example` define the ones that should be provided?

2017-05-09 09:26 UTC, jonnyshaw89 commented on survey-runner-ecs-application/global_vars.tf
> +  default     = "Z2XIERRF1SJEYP"
its the same that is defined in `survey-runner-application`

2017-05-09 09:28 UTC, jonnyshaw89 commented on survey-runner-ecs-application/global_vars.tf
> +  description = "The address of the postgres database"
This gets provided by `run-terraform.sh` so doesn't need you to provide a value.

2017-05-09 09:28 UTC, jonnyshaw89 commented on survey-runner-ecs-application/global_vars.tf
> +  default     = "digitaleq12345"
the defaults match `survey-runner-database`

2017-05-09 09:30 UTC, jonnyshaw89 commented on survey-runner-ecs-application/iam.tf
> +  policy = "${data.aws_iam_policy_document.survey_runner.json}"
Yeh i need to split these up.

2017-05-09 09:30 UTC, jonnyshaw89 commented on survey-runner-ecs-application/outputs.tf
> +//output "survey_runner_address" {
i will create another branch

2017-05-09 09:30 UTC, jonnyshaw89 commented on survey-runner-ecs-application/outputs.tf
> +output "survey_runner_launcher_address" {
suggestion?

2017-05-09 09:32 UTC, jonnyshaw89 commented on survey-runner-ecs-application/security_groups.tf
> +    from_port   = "0"
Not really as the container will start on a random port.
I can probably narrow the cider_block to just the ALB.

2017-05-09 13:29 UTC, jonnyshaw89 commented on survey-runner-ecs-application/security_groups.tf
> +    from_port   = "0"
I tried locking this down and it failed to join the ECS cluster.

2017-05-12 11:29 UTC, jonnyshaw89 commented
Moved this code to a new Repo https://github.com/ONSdigital/eq-terraform-ecs/pull/1

2017-05-12 11:29 UTC, closed without merging