Refactor to treat different areas of the system as modules
ONSdigital/eq-terraform pull request #80
Opened 2017-05-12 11:10 UTC by jonnyshaw89

### What is the context of this PR?
Have loaded the individual areas of the system in as modules.
This speeds up the creation and destruction of an environment by allowing infrastructure to be provisioned in parallel

A `developer_defaults.tf` file is defined in the root which reduces the amount of configuration required by developers to get an environment up and running

### How to review
Try and deploy an environment by following the README

2017-05-15 16:15 UTC, ajmaddaford requested changes

2017-05-15 16:15 UTC, ajmaddaford commented on README.md
> -  - Export an `AWS_ENVIRONMENT_NAME` environment variable e.g. `export AWS_ENVIRONMENT_NAME=preprod` or `export AWS_ENVIRONMENT_NAME=$USER`
You need to run a `terraform get` to import the modules before the plan. Probably worth mentioning here.

2017-05-15 16:15 UTC, ajmaddaford commented on survey-runner-database/global_vars.tf
>    description = "Route tables with route to NAT gateway"
When I run the `run-terraform.sh` script I get an error:
`variable private_route_table_ids should be type list, got string`

2017-05-15 16:31 UTC, ajmaddaford requested changes

2017-05-15 16:31 UTC, ajmaddaford commented on survey-runner-database/global_vars.tf
>    description = "Route tables with route to NAT gateway"
We need to change the scripts that pass lists to terraform to this format:
`-var 'private_route_table_ids=["<id_1>","<id_2>","<id_3>"]'`

2017-05-16 12:55 UTC, jonnyshaw89 commented
@ajmaddaford i have addressed your comments.

2017-05-17 16:50 UTC, ajmaddaford requested changes

2017-05-17 16:50 UTC, ajmaddaford commented on survey-runner-application/run-terraform.sh
> +private_route_table_ids="[$(aws ec2 describe-route-tables --filters "Name=tag:Environment,Values=${AWS_ENVIRONMENT_NAME}" "Name=tag:Type,Values=Private" --query 'RouteTables[*].RouteTableId' --output
I get an error when running this:
```
invalid value "private_route_table_ids=[rtb-cc1d56ab\",\"rtb-ed13588a\",\"rtb-091c576e\"]"
```
Looks like a missing `"` before the first route table id

2017-05-17 16:50 UTC, ajmaddaford commented
I also get the error:
```
* variable public_subnet_ids should be type list, got string
```

2017-05-18 11:42 UTC, ajmaddaford approved these changes

2017-05-18 15:40 UTC, samiwel approved these changes
Worked for me, with the usual dose of Terraform/AWS fiddly-ness!

2017-05-18 15:51 UTC, merged