Updated Developer scripts to run Survey Runner in ECS
ONSdigital/eq-terraform pull request #90
Opened 2017-07-31 08:49 UTC by jonnyshaw89

### What is the context of this PR?
Have added the Survey Runner and Survey Launcher deploy modules and updated developer defaults to make them work

### How to review
Run `terraform apply` like normal

2017-08-01 13:06 UTC, ajmaddaford requested changes

2017-08-01 13:06 UTC, ajmaddaford commented on developer_defaults.tf
> +variable "survey_runner_s3_secrets_bucket" {
This variable should be moved next to all the other Survey Runner on ECS specific variables. Also, I think the comment above this line should be `Survey Runner on Elastic Beanstalk`

2017-08-01 13:06 UTC, ajmaddaford commented on developer_defaults.tf
> +# Survey Runner
I think this comment should be `Survey Runner on ECS`

2017-08-01 13:06 UTC, ajmaddaford commented on survey-runner.tf
> +  secrets_file_name       = "${var.secrets_file_name}"
These variables should be namespaced with `survey_runner_` to be consistent with the launcher variables below

2017-08-01 13:06 UTC, ajmaddaford commented on survey-runner.tf
>  module "survey-runner-ecs" {
We should rename this something like `eq-ecs`

2017-08-01 13:06 UTC, ajmaddaford commented on survey-runner.tf
> +module "survey-launcher-new" {
I think we should use some clearer naming for the modules, something like:
```
survey-runner-on-elastic-beanstalk
survey-runner-on-ecs
survey-launcher-for-elastic-beanstalk
survey-launcher-for-ecs
```

2017-08-02 15:51 UTC, adoublebarrel approved these changes
LGTM

2017-08-03 07:30 UTC, ajmaddaford commented
All looks good 👍 

I'll leave my blocking review until https://github.com/ONSdigital/eq-survey-launcher-deploy/pull/1 and https://github.com/ONSdigital/eq-terraform-ecs/pull/5 get merged and the module references in this pull request are updated.

2017-08-03 08:58 UTC, dwyeradam approved these changes

2017-08-03 15:56 UTC, ajmaddaford approved these changes

2017-08-03 15:56 UTC, merged