Added documentation on how to deploy a branch
ONSdigital/eq-terraform pull request #93
Opened 2017-08-16 16:16 UTC by adoublebarrel

### What is the context of this PR?

Added documentation on how to deploy a branch so that PO and design reviews/in flight feedback can be done without the developers laptop.

### How to review

Follow the "Deploying a branch" section of the readme

- Does it make sense?
- Does it work?

2017-08-17 15:06 UTC, jonnyshaw89 requested changes

2017-08-17 15:06 UTC, jonnyshaw89 commented on README.md
> +## Deploying a branch
`Deploying a Survey Runner branch`?

2017-08-18 12:38 UTC, jonnyshaw89 approved these changes

2017-08-21 10:22 UTC, dwyeradam approved these changes

2017-08-21 14:38 UTC, merged