eq snapshot jenkins server initial files
ONSdigital/eq-terraform pull request #94
Opened 2017-08-17 08:21 UTC by berianjones

### What is the context of this PR?
Added new directory jerkins-snapshot, which is intended to snapshot the jenkins-preprod instance
### How to review
create a ec2 server instance (nano is fine) called jenkins-preprod-eqdevelopment.
In eq-terraform, cd to jenkins-snaphot
run terraform init or terraform get to bring in the ebs_bckup module.
amend the developer_defaults.tf file to change the minutes in the cron variable (I add about 3 - 4 minutes to the current time to allow time for the lambda function to be built)
You'll need to supply the was_instance key the was secret key and the zone which is "dev.eq.ons.digital"

a snapshot should be created.

I'm aware that I'll probably need to amend the name of the instance to either jenkins-${var.env} or even hard code to jenkins-preprod for the real thing, but I'm looking to see I haven't missed anything else. Once this is passed, I'll create the jenkins job .

### Who worked on the PR

2017-08-17 15:07 UTC, jonnyshaw89 requested changes

2017-08-17 15:07 UTC, jonnyshaw89 commented on jenkins-snapshot/developer_defaults.tf
> +variable "env" {
the concept of `developer_defaults.tf` won't work for this as its going to be run from this folder?
You should rename this file to `global_vars.tf`

2017-08-17 15:07 UTC, jonnyshaw89 commented on jenkins-snapshot/developer_defaults.tf
> +variable "ecs_instance_type" {
Do you need ECS variables?

2017-08-17 15:07 UTC, jonnyshaw89 commented on jenkins-snapshot/ebs.tf
> +  unique_name      = "berian-test"
this should be something like `jenkins_ebs_snapshot`

2017-08-17 15:07 UTC, jonnyshaw89 commented on jenkins-snapshot/ebs.tf
> +  EC2_INSTANCE_TAG = "${var.env}-jenkins"
this value only needs to match a tag value for the EC2 instance so there is no need to rename the instance. with the RabbitMQ servers we have a tag of `Service = "${var.env}-RabbitMQ"` so this could be Service = "${var.env}-Jenkins" for this?

2017-08-17 15:07 UTC, jonnyshaw89 commented on jenkins-snapshot/example.tf
> +  access_key = ""
these need to be populated via `${var.aws_access_key}`

2017-08-17 15:07 UTC, jonnyshaw89 commented on jenkins-snapshot/run-terraform.sh
> +export ANSIBLE_HOST_KEY_CHECKING=False
Do you need this export?

2017-08-17 15:07 UTC, jonnyshaw89 commented on jenkins-snapshot/terraform.tfvars.examples
> +slack_webhook_path = ""
I don't think you need these bottom 3?

2017-08-17 17:30 UTC, berianjones commented on jenkins-snapshot/terraform.tfvars.examples
> +slack_webhook_path = ""
Yes thanks for the comments. This was what I needed, I'll make the changes

2017-08-23 13:05 UTC, jonnyshaw89 commented
Closing this PR as this code shouldn't even love in this repo as the code in this repo doesn't deploy Jenkins

2017-08-23 13:05 UTC, closed without merging